# Generated by Django 4.2.30 on 2026-06-20 16:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chats', '0002_message_is_seen_message_receiver'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='deleted_by',
            field=models.ManyToManyField(blank=True, related_name='deleted_chats', to=settings.AUTH_USER_MODEL),
        ),
    ]
