# Generated by Django 4.2.30 on 2026-06-19 16:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('TEXT', 'Text Status'), ('IMAGE', 'Image'), ('VIDEO', 'Video')], default='TEXT', max_length=10)),
                ('media_file', models.FileField(blank=True, null=True, upload_to='status/')),
                ('text_content', models.TextField(blank=True, null=True)),
                ('background_color', models.CharField(blank=True, default='#128c7e', max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StatusView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='status.status')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('status', 'user')},
            },
        ),
    ]
